version: "3"

# Define the services/containers to be run
services:
  client: # name of the first service
    build: ./ # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - ./app # this will enable changes made to the angular app reflect in the container
