name: Open Grants CI
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn dapp:build
        env:
          REACT_APP_INFURA_ID: ${{ secrets.INFURA_ID }}

      - name: Deploy to Firbase ${{ DEPLOYMENT }}
        uses: w9jds/firebase-action@master
        with:
          args: use ${{ DEPLOYMENT }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
