name: Open Grants CI
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Fetch Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: nodeModules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn dapp:build
        env:
          REACT_APP_INFURA_ID: ${{ secrets.INFURA_ID }}
          REACT_APP_NETWORK: kovan

      - name: Deploy for Kovan Testnet
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project=kovan
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
